# Generated by Django 4.2.1 on 2023-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_alter_contact_address_alter_contact_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
