# Generated by Django 4.2.1 on 2023-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0004_alter_contact_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
