# Generated by Django 4.2.1 on 2023-05-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0006_alter_file_user_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user_file_name',
        ),
    ]
