# Generated by Django 4.2.1 on 2023-05-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0007_remove_file_user_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_choice_file_name',
            field=models.CharField(default='new_file', max_length=255),
        ),
    ]
