# Generated by Django 4.2.1 on 2023-05-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0008_file_user_choice_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user_choice_file_name',
            new_name='choice_file_name',
        ),
    ]
