# Generated by Django 4.2.1 on 2023-05-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0009_rename_user_choice_file_name_file_choice_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='choice_file_name',
        ),
    ]
