# Generated by Django 4.2.1 on 2023-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0010_remove_file_choice_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.TextField(),
        ),
    ]
