# Generated by Django 4.2.1 on 2023-05-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0012_file_dropbox_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_url',
        ),
    ]
